stages:
  - test

test:
  stage: test
  image: python:3.12-alpine
  before_script:
    - apk add --no-cache gcc musl-dev python3-dev linux-headers
    - pip install --upgrade pip
    - pip install hatch  
  script:
    - pytest --cov=test_gcd.py --cov-report=term-missing --cov-report=xml  # Remplacez <nom_du_module> par le nom de votre module principal
  coverage: '/\d+%/'