stages:
  - test
  - deploy-stable
  - deploy-develop

test:
  stage: test
  image: python:3.12-alpine
  before_script:
    - apk add --no-cache gcc musl-dev python3-dev linux-headers
    - pip install --upgrade pip
    - pip install hatch pytest pytest-cov
  script:
    - pytest --cov=src/my_arithmetic_faizandier --cov-report=term-missing --cov-report=xml
  coverage: '/\d+%/'  

deploy_stable:
  stage: deploy-stable
  image: python:3.12-alpine
  before_script:
    - apk add --no-cache gcc musl-dev python3-dev linux-headers
    - pip install --upgrade pip
    - pip install hatch
  script:
    - echo "my-arithmetic-faizandier deployment on stable servers"
    - hatch build
    - echo "Contenu du dossier dist/"
    - ls dist/
  only:
    - tags
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

deploy_develop:
  stage: deploy-develop
  image: python:3.12-alpine
  before_script:
    - apk add --no-cache gcc musl-dev python3-dev linux-headers
    - pip install --upgrade pip
    - pip install hatch
  script:
    - echo "my-arithmetic-faizandier deployment on develop branch (non-stable servers)"
    - hatch build
    - echo "Contenu du dossier dist/ pour la branche develop"
    - ls dist/
  only:
    - develop
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
